version: 1.0.{build}
configuration: release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services:
  - mssql2014
before_build:
- cmd: >-
    nuget restore JsPlc.Ssc.Link\Link.sln

    copy /y JsPlc.Ssc.Link\JsPlc.Ssc.Link.Service.Tests\App-Appveyor.config JsPlc.Ssc.Link\JsPlc.Ssc.Link.Service.Tests\App.config



build:
  project: JsPlc.Ssc.Link\Link.sln
  publish_wap: true


choco install msbuild-sonarqube-runner -y


MSBuild.SonarQube.Runner.exe begin

/k:%Link% 
/n:%sonar-integration01% 
/v:%GitVersion_FullSemVer% 
/d:sonar.host.url=%http://52.51.78.161% 
/d:sonar.login=%appveyor%
/d:sonar.password=%sonar%

MSBuild.SonarQube.Runner.exe end

#deploy:
#- provider: Environment
#  name: Link-development
#notifications:
#- provider: Slack
#  incoming_webhook: https://hooks.slack.com/services/T03J4B99C/B0MDF5XH9
#  UgekfTj9HSj1SE9fWRaLHN3Q
#  channel: Link
#  on_build_success: true
#  on_build_failure: true
#  on_build_status_changed: true

