version: 1.0.{build}
configuration: release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
services:
  - mssql2014
before_build:
- cmd: >-
    nuget restore JsPlc.Ssc.Link\Link.sln

    copy /y JsPlc.Ssc.Link\JsPlc.Ssc.Link.Service.Tests\App-Appveyor.config JsPlc.Ssc.Link\JsPlc.Ssc.Link.Service.Tests\App.config

    choco install msbuild-sonarqube-runner -y

    cd %APPVEYOR_BUILD_FOLDER%\JsPlc.Ssc.Link

    MSBuild.SonarQube.Runner.exe begin /k:Link /n:LinkProject /v:1.1 /d:sonar.host.url=http://52.51.78.161:80 /d:sonar.login=appveyor /d:sonar.password=sonar

build:
  project: Link.sln
  publish_wap: true
after_build:
- cmd: MSBuild.SonarQube.Runner.exe end
#deploy::
#- provider: Environment
#  name: Link-development

