//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsPlc.Ssc.Link.Portal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsPlc.Ssc.Link.Portal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Development.
        /// </summary>
        public static string ColleagueSectionHeader {
            get {
                return ResourceManager.GetString("ColleagueSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation tracker.
        /// </summary>
        public static string ConvTracker {
            get {
                return ResourceManager.GetString("ConvTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link conversations.
        /// </summary>
        public static string LinkConversations {
            get {
                return ResourceManager.GetString("LinkConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My objectives.
        /// </summary>
        public static string MyObjectives {
            get {
                return ResourceManager.GetString("MyObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My personal development plan.
        /// </summary>
        public static string MyPdp {
            get {
                return ResourceManager.GetString("MyPdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Team.
        /// </summary>
        public static string TeamSectionHeader {
            get {
                return ResourceManager.GetString("TeamSectionHeader", resourceCulture);
            }
        }
    }
}
